# Site
title:              Carlos A. Planchón
bio:                'I.T enthusiast, programmer, blogger.'
description:        "Any sufficiently advanced technology is indistinguishable from biology."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me_beach_2019.jpg'
background:         'assets/img/punta_gorda_background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://carlosplanchon.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   carlosplanchon

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  analytics: UA-135543704-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
# twitter:            carlosplanchon
facebook:           carlosplanchon
github-url:         carlosplanchon
#stackoverflow:     username
linkedin:           carlosplanchon
#xing:              username
instagram:          carlos.planchon
#lastfm:            username
#tumblr:            username
# medium:            '@carlosplanchon'
# pinterest:         carlos_planchon
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
